### ISSUE TITLE
SyntaxError: Unexpected token export

### ISSUE THREAD

**Issue by Daffko** [Promact/md2#192]
Hi,

I'm experiencing the same bug as in #53 
`index.js:1 Uncaught SyntaxError: Unexpected token export`

My setup:
`md2@0.0.19`
`"webpack": "^1.15.0"`
`"@angular/core": "^4.1.0"`

Any help, please?
Thanks.

**Comment by janhartmann** [comment]
I get exactly the same.

On line:

```/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//                                                                                                                     //
// node_modules/md2/index.js                                                                                           //
//                                                                                                                     //
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
                                                                                                                       //
export * from './core';     <---
```

**Comment by janhartmann** [comment]
Is it possible to get an update on this issue?

**Comment by dharmeshpipariya-zz** [comment]
@Daffko and @janhartmann we have fixed in the latest release, comment here if any issue

**Comment by Daffko** [comment]
I've updated to most recent version 0.0.24, still getting the same error.

**Comment by dharmeshpipariya-zz** [comment]
@Daffko and @janhartmann we have fixed in the release of md2@0.0.25, comment here if any issue

**Comment by Daffko** [comment]
I've just tested the latest version 0.0.25. It's still crashing on `export * from './core';`
