### ISSUE TITLE
DatePicker MinDate and MaxDate with Time is not working

### ISSUE THREAD

**Issue by praveenrengarajan** [Promact/md2#219]
#### What is the expected behavior?
Should set date & time in Min and Max date attribute. 

#### What is the current behavior?
It's accepting only date but not setting time.

#### What are the steps to reproduce?

Providing a Plunker (or similar) is the *best* way to get the team to see your issue.
Plunker template: http://plnkr.co/edit/rQmUz8WYRh5Vz4gwY8E4?p=info

**Comment by dharmeshpipariya-zz** [comment]
@praveenrengarajan which version of md2 and angular you have used?

**Comment by praveenrengarajan** [comment]
@dharmeshpipariya  md2: 0.0.17 and angular 2.4.9

**Comment by dharmeshpipariya-zz** [comment]
@praveenrengarajan you have to update md2 with the latest version and use angular 4.\*.\*, we have fixed it in latest release

**Comment by megamind2301** [comment]
@dharmeshpipariya  I am using md2:0.0.21 and Angular4.\*.\*, but max attribute in datetime type is still not working. I was about to create issue but found it already exists! 
P.S. It does work when I play with md2 git master repo.
