### ISSUE TITLE
Unable to load transpiler to transpile http://localhost:5555/node_modules/md2/index.js

### ISSUE THREAD

**Issue by amalshehu** [Promact/md2#31]
I am trying to integrate md2 with angular seed .But i'm getting these following errors.
Seed info :https://github.com/mgechev/angular-seed

### My project.config.ts file

```
import { join } from 'path';

import { SeedConfig } from './seed.config';

/**
 * This class extends the basic seed configuration, allowing for project specific overrides. A few examples can be found
 * below.
 */
export class ProjectConfig extends SeedConfig {

  PROJECT_TASKS_DIR = join(process.cwd(), this.TOOLS_DIR, 'tasks', 'project');

  constructor() {
    super();
    //this.APP_TITLE = 'Put name of your app here';


    /* Enable typeless compiler runs (faster) between typed compiler runs. */
    // this.TYPED_COMPILE_INTERVAL = 5;

    // Add `NPM` third-party libraries to be injected/bundled.
    this.NPM_DEPENDENCIES = [
      ...this.NPM_DEPENDENCIES,
      /* Select a pre-built Material theme */
     {src: '@angular/material/core/theming/prebuilt/indigo-pink.css', inject: true},
      // {src: 'jquery/dist/jquery.min.js', inject: 'libs'},
      // {src: 'lodash/lodash.min.js', inject: 'libs'},
    ];

    // Add `local` third-party libraries to be injected/bundled.
    this.APP_ASSETS = [
      ...this.APP_ASSETS,
      // {src: `${this.APP_SRC}/your-path-to-lib/libs/jquery-ui.js`, inject: true, vendor: false}
      // {src: `${this.CSS_SRC}/path-to-lib/test-lib.css`, inject: true, vendor: false},
    ];

    /* Add to or override NPM module configurations: */
    // this.mergeObject(this.PLUGIN_CONFIGS['browser-sync'], { ghostMode: false });
    // add Material configuration to SystemJS.
   this.addPackageBundles({
     name:'@angular/material',
     path:'node_modules/@angular/material/material.umd.js',
     packageMeta:{
       main: 'index.js',
       defaultExtension: 'js'
     }
   });

   // add Material configuration to SystemJS.
  this.addPackageBundles({
    name:'md2',
    path:'node_modules/md2/index.js',
    packageMeta:{
      main: 'md2.umd.js',
      format:'cjs'
    }
  });

  }

}

```
![image](https://cloud.githubusercontent.com/assets/12576673/19956592/663069ee-a1b4-11e6-874e-431e44c3cdd8.png)

**Comment by dharmeshpipariya-zz** [comment]
We have fixed this issue with release md2@0.0.7,
comment here if you have an issue

**Comment by amalshehu** [comment]
Yeah i  still having that issue.Is anything wrong with my project.config.ts?Please advice on the integration with material seed.

**Comment by dharmeshpipariya-zz** [comment]
revert the md2.umd.js and index. js as below snippet
  this.addPackageBundles({
    name:'md2',
    path:'node_modules/md2/md2.umd.js',
    packageMeta:{
      main: 'index.js',
      format:'cjs'
    }
  });

**Comment by amalshehu** [comment]
It's working now. Thanks a lot.
