### ISSUE TITLE
Unexpected token export

### ISSUE THREAD

**Issue by tariknz** [Promact/md2#53]
Hey guys I'm getting this error when trying to run it:

`index.js:1 Uncaught SyntaxError: Unexpected token export`

This is just happening by adding Md2Module.forRoot() in my module.

Using: Angular 2.2.4 with Webpack

**Comment by web265p3** [comment]
I have the same issue :) Probably something with Webpack.

**Comment by xmlguy74** [comment]
I am seeing the same issue. Did you resolve this?

**Comment by mtinnes** [comment]
This is what I'm seeing: **_Uncaught SyntaxError: Unexpected token export_**

It's the first line from the following function which is failing:
```
/***/ },
/* 689 */
/***/ function(module, exports) {

	export * from './core';
	export * from './module';
	export * from './accordion/index';
	export * from './autocomplete/index';
	export * from './chips/index';
	export * from './collapse/index';
	export * from './colorpicker/index';
	export * from './data-table/index';
	export * from './datepicker/index';
	export * from './dialog/index';
	export * from './menu/index';
	export * from './multiselect/index';
	export * from './select/index';
	export * from './tabs/index';
	export * from './tags/index';
	export * from './toast/index';
	export * from './tooltip/index';

	//# sourceMappingURL=index.js.map


/***/ },
```

**Comment by dharmeshpipariya-zz** [comment]
We have fixed the issue with release md2@0.0.13-1,
comment here if you have an issue

**Comment by web265p3** [comment]
I still get the same error message after the update to 0.0.13-1 :-(

-- With Webpack 1.14.0

**Comment by web265p3** [comment]
Anybody else tried it?

**Comment by tariknz** [comment]
Working fine for me now but I'm using Webpack 2.

```
"md2": "0.0.13-1",
"webpack": "2.2.0-rc.4",
```

@web265p3 I recommend npm uninstall the package and reinstalling it just in case something might be lingering around.

**Comment by web265p3** [comment]
I already did this, but with the last stable version of Webpack there is not way. 
But because the only reason Webpack 2 is still in beta is a leak of documentation I also just upgraded and now md2 works like a charm :-)

**Comment by dharmeshpipariya-zz** [comment]
We have fixed the issue with release md2@0.0.14,
comment here if you have an issue

**Comment by marxxxx** [comment]
@dharmeshpipariya after the fix, should it also work with webpack 1.13 or is webpack 2 mandatory?

**Comment by codelovesme** [comment]
I am getting the same error right now. @dharmeshpipariya 
md2 version : 0.0.16
webpack version : 1.13.1

**Comment by dharmeshpipariya-zz** [comment]
We have fixed the issue with release md2@0.0.17,
comment here if you have an issue

**Comment by Daffko** [comment]
I'm having the same issue with release `md2@0.0.19`.
` "webpack": "^1.15.0"`
`"@angular/core": "^4.0.3"`
